import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig, devices } from '@playwright/test'

// One Playwright project per rr-lingui configuration. Each project runs its own
// fixture app (a standalone React Router app under fixtures/<config>/) on a
// dedicated port, so all four configurations run independently and in parallel.
// The fixture apps are generated by scripts/build-fixtures.mjs (run before tests).
//
// The dev server reflects real runtime behavior — middleware redirects, catalog
// loading, the /change-locale action, and cookie/localStorage persistence all
// execute exactly as they would in a user app.

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const CI = !!process.env.CI
// Resolve the react-router CLI from this package's node_modules so the webServer
// can launch it with cwd = the fixture dir.
const reactRouterBin = path.join(__dirname, 'node_modules', '.bin', 'react-router')

type Project = { name: string; port: number; testDir: string }

const projects: Project[] = [
  { name: 'ssr-url-prefix', port: 3101, testDir: './tests/ssr-url-prefix' },
  { name: 'ssr-context', port: 3102, testDir: './tests/ssr-context' },
  { name: 'client-url-prefix', port: 3103, testDir: './tests/client-url-prefix' },
  { name: 'client-context', port: 3104, testDir: './tests/client-context' },
]

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: CI,
  retries: CI ? 2 : 0,
  workers: CI ? 2 : undefined,
  reporter: CI ? [['github'], ['list']] : 'list',
  use: {
    actionTimeout: 30_000,
    navigationTimeout: 30_000,
    trace: 'retain-on-failure',
  },
  // Start all four dev servers up front; each project targets its own baseURL.
  // Fixtures must already be generated (the test script builds them first).
  webServer: projects.map((p) => ({
    command: `"${reactRouterBin}" dev --port ${p.port} --host 127.0.0.1`,
    cwd: path.join(__dirname, 'fixtures', p.name),
    port: p.port,
    path: '/',
    timeout: 180_000,
    reuseExistingServer: false,
  })),
  projects: projects.map((p) => ({
    name: p.name,
    testDir: p.testDir,
    use: {
      baseURL: `http://127.0.0.1:${p.port}`,
      ...devices['Desktop Chrome'],
    },
  })),
})
